version: '3.3'
services:
  aws:
    image: localstack/localstack:latest
    container_name: aws
    ports:
      - "4567-4584:4567-4584"
    volumes:
      - 'aws-storage:/tmp/localstack'
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
volumes:
  aws-storage: