package com.example.dynamodemo.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.example.dynamodemo.request.CreateStudentRequest;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "student")
public class Student implements Serializable {

    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey(attributeName = "student_id")
    @DynamoDBAutoGeneratedKey
    private String studentId;

    @DynamoDBRangeKey(attributeName = "first_name")
    private String firstName;

    @DynamoDBAttribute(attributeName = "last_name")
    private String lastName;

    public static Student valueOf(CreateStudentRequest createStudentRequest){
        return Student.builder().studentId(createStudentRequest.getStudentId())
                .firstName(createStudentRequest.getFirstName())
                .lastName(createStudentRequest.getLastName())
                .build();
    }
}
